### PR TITLE
github.io

### PR DESCRIPTION
**Pull request by Alexsaphir**
github.io should not be block entirely.

### CODE REVIEW

**Comment by MarcianoFlorian** [comment]
This block many web cdn hosted on github.io . 
Need to be fix ASAP...

**Comment by jfgoncalves** [comment]
Seconding this, this has no business being blocked.

**Comment by IQbrod** [comment]
This does cause production issue on our SaaS

**Comment by smed79** [comment]
False positive, fixed in https://github.com/easylist/listefr/commit/22904e9265a27eba6296ed31dfcc0b6e49d2cc97

Sorry for the inconvenience :pray:

**Pull request closed without merging**
